name: Deployment to NPM registry
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_CHANGESET_TOKEN }}
      - name: Setting up Node.js...
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Installing dependencies...
        run: yarn --frozen-lockfile
      - name: Running tests...
        run: yarn test
      - name: Building...
        run: yarn build
      - name: Deploying to NPM registry...
        run: npm publish --access public --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CHANGESET_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CHANGESET_TOKEN }}
