name: Testing on Pull Request
on:
  pull_request:
    types: [opened, synchronize, edited]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setting-up Node.js...
        uses: actions/setup-node@v2
        with:
          node-version: 22
      - name: Installing dependencies...
        run: yarn --frozen-lockfile
      - name: Running tests...
        run: yarn test
